### ISSUE TITLE
ability to overwrite asset instead of merge

### ISSUE THREAD

**Issue by bsushmith** [odpf/compass#160]
**Is your feature request related to a problem? Please describe.**
As part of [UpdatePatchAsset](https://github.com/odpf/compass/blob/main/internal/server/v1beta1/asset.go#L215), we [patch](https://github.com/odpf/compass/blob/main/internal/server/v1beta1/asset.go#L237) and merge the asset before writing into DB. 

For the asset field `data` which contains the crux of asset information, it is impossible to overwrite in the current code. Only if the existing asset data is nil, it is possible to overwrite it. Otherwise, the existing `asset.data` is [merged](https://github.com/odpf/compass/blob/main/core/asset/patch.go#L100) with incoming changes before writing to DB.

Would like to have a feature flag, where the user can decide if they would like to always take it in the latest changes or merge it with existing values. 

**Describe the solution you'd like**
A feature flag to decide whether to merge or take it latest changes without merging.

**Describe alternatives you've considered**
I wanted to remove preview rows for bigquery tables in a project, and configured `meteor` recipe in such a way by having `max_preview_rows` value set as 0.  But since compass does only merge rather than overwrite, it didn't happen. I've tried to delete the asset and then insert the asset again. but since the `DeleteAsset` takes in asset id, it became cumbersome to delete all the assets using the id. 

**Additional context**
Am not sure about the process of finding asset `diff` here - https://github.com/odpf/compass/blob/main/internal/store/postgres/asset_repository.go#L301. By the time, the code flow reaches here, the asset is already merged with incoming changes. This diff is used to track asset versions in `asset_versions` table.
 Please correct me If I am wrong here, but shouldn't the diff be calculated with incoming changes rather than merged changes?

**Comment by StewartJingga** [comment]
@bsushmith  There are few approaches we can take here

### 1. New API to update/replace asset

`Upsert(UpsertRequest)` -  `[PUT] /v1beta1/assets/{asset_urn}`

Pros:
1. Relatively flexible approach because clients can decide which API suits their needs
2. Will not interfere with current `UpsertPatch` API

Cons:

1. More APIs to maintain
2. Meteor's `compass` sink will need to use 2 APIs alternatively

### 2. New querystring/config on `UpsertPatchAsset` API to define whether to `patch` or `update` asset.

`replace: bool` - `?replace=1`

Pros:

1. Relatively flexible approach because clients can decide which strategy to use
2. Still one API to maintain for upserting asset

Cons:

1. `UpsertPatchAsset` API will be more complex
2. Meteor's `compass` sink will still need changes

### 3. New feature flag or config on `Compass` server to set the strategy when upserting asset.

New `UPSERT_STRATEGY: "patch" | "replace"` config on Compass server

Pros:

1. Meteor won't need any changes

Cons:

1. Not so flexible approach because to change strategy you will need to restart compass server

**Comment by bsushmith** [comment]
@StewartJingga I'm inclined towards option2. `query flag` based option feels right in this case.

**Comment by StewartJingga** [comment]
@bsushmith some of the downside of options 2 are:

- the API could become more complex as now it should handling two cases, replace or merging
- they both will have different validations which could be tricky compared to splitting them into two different APIs

**Comment by ravisuhag** [comment]
@StewartJingga which approach we are taking here?
